name: atlantis

services:
  api:
    container_name: atlantis-api
    image: ${DOCKER_IMAGE_URL}/api:${DOCKER_IMAGE_TAG:-latest}
    build:
      context: api
      dockerfile: Dockerfile.prod
      args:
        - UID=${UID}
        - GID=${GID}

    depends_on:
      redis:
        condition: service_started
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:5000/health'', timeout=5).read()"',
        ]
      timeout: 20s
      interval: 20s
      retries: 2
    networks:
      - supabase_network_atlantis
    ports:
      - 59111:5000
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ${HOME}/.atlantis
        target: /mnt/data
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      DOCKER_IMAGE: ${DOCKER_IMAGE_URL}/api:${DOCKER_IMAGE_TAG:-latest}
      REDIS_URL: redis://redis:6379
      SUPABASE_DB_URL: postgresql://postgres:postgres@supabase_db_atlantis:5432/postgres
      SUPABASE_SECRET_KEY: sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz
      SUPABASE_URL: http://supabase_kong_atlantis:8000

  redis:
    container_name: atlantis-redis
    image: redis/redis-stack-server:latest
    networks:
      - supabase_network_atlantis
    restart: always

networks:
  supabase_network_atlantis:
    external: true
