mutation ATL_CommandsCreateTModLoader_CreateTModLoader(
  $path: String!
  $steamAppBetaBranch: String
  $gameAutocreate: Int!
  $gameDifficulty: Int
  $gameMotd: String
  $gamePassword: String
  $gameSeed: String
) {
  createTmodloader(
    path: $path
    steamAppBetaBranch: $steamAppBetaBranch
    gameAutocreate: $gameAutocreate
    gameDifficulty: $gameDifficulty
    gameMotd: $gameMotd
    gamePassword: $gamePassword
    gameSeed: $gameSeed
  ) {
    path
    steamAppBetaBranch
    gameAutocreate
    gameDifficulty
    gameMotd
    gamePassword
    gameSeed
    manifestType
    manifestVersion
  }
}

query ATL_CommandsCreateTModLoader_DisplayTModLoaderDirectories {
  displayTmodloaderDirectories
}
