mutation ATL_CommandsCreateTerraria_CreateTerraria(
  $steamAppBetaBranch: String
  $gameAutocreate: Int!
  $gameDifficulty: Int
  $gameMotd: String
  $gamePassword: String
  $gameSeed: String
) {
  createTerraria(
    steamAppBetaBranch: $steamAppBetaBranch
    gameAutocreate: $gameAutocreate
    gameDifficulty: $gameDifficulty
    gameMotd: $gameMotd
    gamePassword: $gamePassword
    gameSeed: $gameSeed
  ) {
    path
    steamAppBetaBranch
    gameAutocreate
    gameDifficulty
    gameMotd
    gamePassword
    gameSeed
    manifestType
    manifestVersion
  }
}
