mutation ATL_CommandsCreateTerraria_UpdateTerraria(
  $path: String!
  $steamAppBetaBranch: String
  $gameAutocreate: Int
  $gameDifficulty: Int
  $gameMotd: String
  $gamePassword: String
  $gameSeed: String
) {
  updateTerraria(
    path: $path
    steamAppBetaBranch: $steamAppBetaBranch
    gameAutocreate: $gameAutocreate
    gameDifficulty: $gameDifficulty
    gameMotd: $gameMotd
    gamePassword: $gamePassword
    gameSeed: $gameSeed
  ) {
    path
    steamAppBetaBranch
    gameAutocreate
    gameDifficulty
    gameMotd
    gamePassword
    gameSeed
    manifestType
    manifestVersion
  }
}

query ATL_CommandsCreateTerraria_DisplayTerraria {
  displayTerraria {
    path
    steamAppBetaBranch
    gameAutocreate
    gameDifficulty
    gameMotd
    gamePassword
    gameSeed
    manifestType
    manifestVersion
  }
}
