[project]
name = "atlantis-api"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "aiodocker>=0.24.0",
    "asyncpg>=0.30.0",
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "packaging>=25.0",
    "pydantic>=2.13.4",
    "redis>=6.4.0",
    "strawberry-graphql[fastapi]>=0.278.1",
    "supabase>=2.18.1",
    "uvicorn[standard]>=0.35.0",
    "vdf>=3.4",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.16",
    "mcstatus>=11.0.0",
    "pytest-asyncio>=0.25.0",
    "pytest-xdist>=3.6.0",
    "pytest>=8.3.0",
    "ruff>=0.12.8",
    "ty>=0.0.1a17",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.uv]
package = false

[tool.uv.workspace]
members = []

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py314"
fix = true
src = [".", "src", "test"]
extend-include = ["*.ipynb"]
extend-exclude = [".venv", "src/persistence/schema/generated.py"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "lf"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ARG00",
    "C901",
    "CPY001",
    "D10",
    "ERA001",
    "PLR0912",
    "PLR0913",
    "TC001",
    "TC002",
    "TC003",
    "TD",
    "UP037",
]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"test/**/*.py" = [
    "S101",
    "ARG",
    "PLR2004",
    "SLF001",
    "D",
    "T201",
]

[tool.ty.src]
include = ["src", "test"]
